apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity: #capacity dumy and only for syntax
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName:  #This should be empty in static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-084d2d8329da39260   #volume manamu create chesina file system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 5Gi