apiVersion: v1
kind: Service
metadata:
  name: sc-headless-svc #name we should give
  labels:  # we should give
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:  # we should give
    purpose: statefulset
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: sc-normal-svc #name we should give
  labels:  # we should give
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  selector:  # we should give
    purpose: statefulset
    project: roboshop
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-headless # we give
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "sc-headless-svc" # we should give and this should be headless service
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels: # we should give and will maintain same labels in all
        purpose: statefulset
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # this is nothing but pvc,you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs" # we should give
      resources:
        requests:
          storage: 2Gi